# todo-app/docker-compose.dev.yml

services:
  app:
    image: todo-frontend-dev
    volumes:
      - ./todo-frontend:/usr/src/app
    ports:
      - 5173:5173
    container_name: todo-frontend-dev
  nginx:
    image: nginx:1.25-alpine
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: nginx-reverse-proxy
    depends_on:
      - app
